title: "Welcome to the blog"
date: 2019-01-27
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Github pages with jekyll. Learn git thourgh github learning lab https://lab.github.com/
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
